### PR TITLE
Smaller build

### PR DESCRIPTION
**Pull request by chandlerprall**
~300 bytes off the minified version and ~100 bytes off the zip

### CODE REVIEW

**Comment by mneubrand** [comment]
Looks good at first glance. Probably going to merge this tomorrow

**Comment by maettig** [comment]
Typo in "repeatSweep", should be "repeatSpeed". And the JavaDoc comment for setSettings() needs a little love. I was also wondering why you are working with characters instead of simply using the numeric array indices. Turns out the compiled result would be ~80 bytes bigger because of the many square brackets needed.

**Comment by chandlerprall** [comment]
Fixed the typo @maettig pointed out and updated the function doc.

**Comment by chandlerprall** [comment]
This also needs an update to README.md because of the change from String to Array. How would you like this communicated?

**Comment by mneubrand** [comment]
Updated README.md, demo.html and jsFiddle linked from the README.md to work with the improved version.

Credit is given in README.md

**Pull request merged**
